services:
  - type: static_site
    name: re-frontend
    repo: https://github.com/SER-515-Group1-Repo/SER515-Group1-Frontend-Repo
    branch: main
    env: static
    buildCommand: npm ci && npm run build
    publishPath: dist
    autoDeploy: true
    envVars:
      - key: VITE_BASE_URL
        value: https://<your-backend-url>
        # NOTE: replace this with your backend URL after deployment
        # You can also set this value using the Render UI as a secret.
